Port the changes made to travis configuration in #159 to GitHub workflows
This should fix the build failures due to unavailable components, e.g.

error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly
Sometimes not all components are available in any given nightly.